name: pictotap
description: A communication app for accessibility.
publish_to: none
version: 1.1.0
homepage: https://endika.github.io/pictotap
repository: https://github.com/endika/pictotap
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  share_plus: ^12.0.1
  path_provider: ^2.1.0
  web: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/background/
    - assets/keyboard/
    - assets/keyboard/descriptive/
    - assets/keyboard/people/
    - assets/keyboard/prepositions/
    - assets/keyboard/some/
    - assets/keyboard/substantive/
    - assets/keyboard/verbs/
